version: "3"

services:
  mongo-database:
    image: mongo:4
    container_name: mongo-database
    restart: on-failure:5
    volumes:
      - ./mongo-database:/data/db
    environment:
      MONGO_INITDB_DATABASE: floor-diagram-db
    ports:
      - 27017:27017
    networks:
      - floor-diagram

  floor-diagram-server:
    image: floor-diagram-server
    container_name: floor-diagram-server
    restart: on-failure:5
    ports:
      - 5000:5000
    depends_on:
      - mongo-database
    environment:
      MAX_IMAGE_UPLOAD_SIZE: 20971520
      SERVER_PORT: 5000
      FRONT_END_URL: your-domain
      MONGODB_URL: mongodb://mongo-database:27017/floor-diagram-db
      DATABASE_HOST: mongo-database
      DATABASE_PORT: 27017
      DATABASE_NAME: floor-diagram-db
      JWT_KEY:
      JWT_LIFE_ACCESS_TOKEN: 3d

    build:
      context: ./floor-diagram-server
    networks:
      - floor-diagram

  floor-diagram-client:
    image: floor-diagram-client
    container_name: floor-diagram-client
    restart: on-failure:5
    ports:
      - 80:80
      - 443:443
    depends_on:
      - floor-diagram-server
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    build:
      context: ./floor-diagram-client
      args:
        - REACT_APP_API_URL= http://localhost:5000
    networks:
      - floor-diagram

networks:
  floor-diagram:
    driver: bridge
volumes:
  mongo-database:
